### ISSUE TITLE
IMPORTANT - Blacklisted from EcoleDirecte API

### ISSUE THREAD

**Issue by Truiteseche** [Brythzz/ec.bryth.dev#4]
Everyone is french here but let's speak english for no reason,

You may have seen it, but currently, we can't log in with our credentials. It displays "Identifiants invalides" (wrong credentials), BUT actually, it's the EcoleDirecte API which responds with this message because the website has probably been blacklisted. Try it yourself and keep me informed.

I'm one of the owners of [Ecole Directe Plus](https://github.com/Magic-Fishes/Ecole-Directe-Plus), and we are facing the exact same issue.

Hope we'll find a solution

**Comment by Truiteseche** [comment]
In fact, there might be solutions. Actually, you can switch your retrieval system from a direct API ED request to a proxy server that would retrieve the data for you. This way they won't be able to catch you with CORS and you will be able to modify the header information that identifies your website, in order to bypass the restrictions.
Concerning us, we already use a proxy, but we are also ignored by ED which recognizes us thanks to our IP address. One solution would be to change our IP address every time we are blacklisted.
For you, a solution would be to first switch to a proxy system until you get blacklisted and have to change your IP address.

What do you think about it ?

If you want to communicate in a more private and straightforward way, here is my discord : truite_seche

**Comment by Brythzz** [comment]
Hey there,

Thank you for opening an issue, I was not aware of the situation as I don't use the site myself anymore.
I don't have much time to maintain this repo but sent your a friend request if you want to continue this discussion

Best
